version: '3.8'

services:
  mcp_server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
      - ./data:/app/data
    environment:
      - API_KEY=test_key
      - MAX_RETRIES=3
      - RETRY_DELAY=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3 