"""Rename model_metadata to config

Revision ID: 07d9f75f2693
Revises: 6f3040f87147
Create Date: 2025-04-13 01:49:23.197332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '07d9f75f2693'
down_revision: Union[str, None] = '6f3040f87147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('config', sa.JSON(), nullable=True))
    op.drop_column('models', 'model_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('model_metadata', sqlite.JSON(), nullable=True))
    op.drop_column('models', 'config')
    # ### end Alembic commands ###
