"""Add total_tokens to ModelRecord

Revision ID: 6f3040f87147
Revises: 56fd2bc03420
Create Date: 2025-04-13 01:48:29.054619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f3040f87147'
down_revision: Union[str, None] = '56fd2bc03420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('total_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'total_tokens')
    # ### end Alembic commands ###
