apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-config
data:
  # Redis Configuration
  REDIS_HOST: "redis"  # This is the Kubernetes service name
  REDIS_PORT: "6379"
  REDIS_SSL: "false"
  
  # MCP Server Configuration
  MCP_SERVER_HOST: "0.0.0.0"
  MCP_SERVER_PORT: "8080"
  MCP_SERVER_URL: "http://mcp-server:8080"  # Internal Kubernetes DNS
  
  # Logging Configuration
  LOG_LEVEL: "INFO"
  LOG_DIR: "/logs"
  
  # Environment
  IN_KUBERNETES: "true"
  
  # S3 Configuration (if using S3 for logs)
  S3_SERVER: ""  # Your S3 endpoint
  S3_BUCKET_NAME: ""  # Your bucket name
  S3_OUTPUT_FOLDER: "mcp-logs"
  S3_VERIFY_SSL: "true" 